"""add user_id relation

Revision ID: 532b801ce341
Revises: 737095956da5
Create Date: 2026-04-06 20:52:25.821824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '532b801ce341'
down_revision: Union[str, Sequence[str], None] = '737095956da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'transactions',
        sa.Column('user_id', sa.UUID(), nullable=True)
    )

    # ✅ STEP 2: Then add foreign key
    op.create_foreign_key(
        'fk_transactions_user_id',
        'transactions',
        'users',
        ['user_id'],
        ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'user_id')
    # ### end Alembic commands ###
